laserscan_toolbox_node:
  ros__parameters:
    #common
    rate: 20.0 #hz
    topic_out: "scan" 
    new_frame: "base_link"

    #debugging
    debug: false
    debug_file_path: "lasertoolbox_debug.txt"
    show_ranges: false

    #output settings
    angle_min: 0.0
    angle_max: 6.283185307
    angle_increment: 0.017453293 #0.017453293 for 360 values resolution
    range_min: 0.0 #m
    range_max: 100.0 #m

    #advanced output settings
    auto_set: true #If true, the seetings below will be set automatically using the first source
    time_increment: 0.0 #s
    scan_time: 0.0 #s

    #sources
    sources: s1 s2 s3 #choose the names you want

    s1: #name of the source you want to set
      topic: "scan1" #topic to subscribed for the LaserScan message
      start_angle: 0.0 #Crop the datas 
      end_angle: 6.283185307 #Crop the datas
      scan_angle_offset: 0.0 #If there is an offset between your frame angle origin (x axis) and your sensor.
      range_min: 0.0 #m, #Crop the datas 
      range_max: 100.0 #m, #Crop the datas 
      persistence: false
      timeout: 0.0 #0.0 seconds = all value's date are autorized

    s2:
      topic: "scan2"
      start_angle: 0.0
      end_angle: 6.283185307

    s3:
      topic: "scan3"
      start_angle: 0.0
      end_angle: 6.283185307
      scan_angle_offset: 0.0